version: '3'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    networks:
      redis-network:
        ipv4_address: 172.20.0.2

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
    networks:
      redis-network:
        ipv4_address: 172.20.0.3

networks:
  redis-network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/16
         gateway: 172.20.0.1
